// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjhY6gu-JEHbDvLQibrFAgz2otynjEbqI',
    appId: '1:824732786303:web:7b5037eb8d8f497e99e94a',
    messagingSenderId: '824732786303',
    projectId: 'hemody-6bb1d',
    authDomain: 'hemody-6bb1d.firebaseapp.com',
    storageBucket: 'hemody-6bb1d.firebasestorage.app',
    measurementId: 'G-SS8YYE9CMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChdWhqKSdlC3dhPVccEfk2GQQtXwLaaII',
    appId: '1:824732786303:android:d9764b58b0761f8499e94a',
    messagingSenderId: '824732786303',
    projectId: 'hemody-6bb1d',
    storageBucket: 'hemody-6bb1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZmnnororIkj8ZkGtsEP7o6ARXZwBzR7c',
    appId: '1:824732786303:ios:ed5090775777d29099e94a',
    messagingSenderId: '824732786303',
    projectId: 'hemody-6bb1d',
    storageBucket: 'hemody-6bb1d.firebasestorage.app',
    iosBundleId: 'com.example.herodydemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZmnnororIkj8ZkGtsEP7o6ARXZwBzR7c',
    appId: '1:824732786303:ios:ed5090775777d29099e94a',
    messagingSenderId: '824732786303',
    projectId: 'hemody-6bb1d',
    storageBucket: 'hemody-6bb1d.firebasestorage.app',
    iosBundleId: 'com.example.herodydemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjhY6gu-JEHbDvLQibrFAgz2otynjEbqI',
    appId: '1:824732786303:web:739d3f6591e8075899e94a',
    messagingSenderId: '824732786303',
    projectId: 'hemody-6bb1d',
    authDomain: 'hemody-6bb1d.firebaseapp.com',
    storageBucket: 'hemody-6bb1d.firebasestorage.app',
    measurementId: 'G-PEL4GQEW9X',
  );
}
